apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: template
  description: A collection of Public Cloud Platform Team templates
spec:
  targets:
    - ./cloud-run-helloworld-python/template.yaml
