name: Build and Deploy to Cloud Run
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]

jobs: 
  #DEV
  CloudRunDeploy:
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    secrets: inherit
  
