apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  namespace: default
  name: demo
spec:
  owner: guests
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.serviceName }}
  description: ${{ values.serviceName }} Deployed to Cloud Run 
  tags:
    - cloudrun
    - gcp
    - python
    - service
  annotations:
    github.com/project-slug: ${{ values.slug }}
    backstage.io/techdocs-ref: dir:.
spec:
  owner: guests
  type: service
  system: demo
  lifecycle: experimental



